export enum GoalTitle {
    ThreeWordsAtOnce = 'Trois en un coup!',
    AtLeastFive = 'Bingo! Enfin presque...',
    FirstToHundred = 'Mister three digits',
    ThirdTimeCharm = 'Répétitif, mais doué!',
    Palindrome = 'Syndrome palindrome',
    ThirtyPointer = 'Trente-ception!',
    NoChangeNoPass = 'Sans relâche',
    NeedOr = 'ChOUette!',
    ThreeWordsAtOnceEn = 'Three at once!',
    AtLeastFiveEn = 'Bingo! well almost...',
    FirstToHundredEn = 'Mister three digits',
    ThirdTimeCharmEn = 'Repetitive but impressive still!',
    PalindromeEn = 'Palindrome mania',
    ThirtyPointerEn = 'Thirty-ception!',
    NoChangeNoPassEn = 'No stopping!',
    NeedOrEn = 'OUh interesting!',
}
